version: '3.8'
services:
    node-express:
        container_name: vsnippet-cors-classic-11
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337